name: Publish Package to npmjs
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g semver jq

      - name: Bump version temporarily
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          LATEST_VERSION=$(npm view "$PACKAGE_NAME" version || echo "0.0.0")
          echo "Latest version: $LATEST_VERSION"
          NEW_VERSION=$(semver -i patch "$LATEST_VERSION")
          echo "Temporary bump to: $NEW_VERSION"
          jq ".version = \"$NEW_VERSION\"" package.json > package.tmp.json
          mv package.tmp.json package.json

      - run: npm ci

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
